#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product_Manufacturing
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Uretim_Tasarım")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertParticle_Operations(Particle_Operations instance);
    partial void UpdateParticle_Operations(Particle_Operations instance);
    partial void DeleteParticle_Operations(Particle_Operations instance);
    partial void InsertWO_Products(WO_Products instance);
    partial void UpdateWO_Products(WO_Products instance);
    partial void DeleteWO_Products(WO_Products instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Product_Manufacturing.Properties.Settings.Default.Uretim_TasarımConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Particle_Operations> Particle_Operations
		{
			get
			{
				return this.GetTable<Particle_Operations>();
			}
		}
		
		public System.Data.Linq.Table<WO_Products> WO_Products
		{
			get
			{
				return this.GetTable<WO_Products>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Particle_Operations")]
	public partial class Particle_Operations : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Op_Record;
		
		private string _Operation_Code;
		
		private string _Operation_Description;
		
		private System.Nullable<System.DateTime> _O_Start_Date;
		
		private System.Nullable<System.DateTime> _O_End_Date;
		
		private string _O_Status;
		
		private string _Station;
		
		private string _O_Track_Code;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOp_RecordChanging(int value);
    partial void OnOp_RecordChanged();
    partial void OnOperation_CodeChanging(string value);
    partial void OnOperation_CodeChanged();
    partial void OnOperation_DescriptionChanging(string value);
    partial void OnOperation_DescriptionChanged();
    partial void OnO_Start_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnO_Start_DateChanged();
    partial void OnO_End_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnO_End_DateChanged();
    partial void OnO_StatusChanging(string value);
    partial void OnO_StatusChanged();
    partial void OnStationChanging(string value);
    partial void OnStationChanged();
    partial void OnO_Track_CodeChanging(string value);
    partial void OnO_Track_CodeChanged();
    #endregion
		
		public Particle_Operations()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Op_Record", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Op_Record
		{
			get
			{
				return this._Op_Record;
			}
			set
			{
				if ((this._Op_Record != value))
				{
					this.OnOp_RecordChanging(value);
					this.SendPropertyChanging();
					this._Op_Record = value;
					this.SendPropertyChanged("Op_Record");
					this.OnOp_RecordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operation_Code", DbType="NVarChar(150)")]
		public string Operation_Code
		{
			get
			{
				return this._Operation_Code;
			}
			set
			{
				if ((this._Operation_Code != value))
				{
					this.OnOperation_CodeChanging(value);
					this.SendPropertyChanging();
					this._Operation_Code = value;
					this.SendPropertyChanged("Operation_Code");
					this.OnOperation_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operation_Description", DbType="NVarChar(150)")]
		public string Operation_Description
		{
			get
			{
				return this._Operation_Description;
			}
			set
			{
				if ((this._Operation_Description != value))
				{
					this.OnOperation_DescriptionChanging(value);
					this.SendPropertyChanging();
					this._Operation_Description = value;
					this.SendPropertyChanged("Operation_Description");
					this.OnOperation_DescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_Start_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> O_Start_Date
		{
			get
			{
				return this._O_Start_Date;
			}
			set
			{
				if ((this._O_Start_Date != value))
				{
					this.OnO_Start_DateChanging(value);
					this.SendPropertyChanging();
					this._O_Start_Date = value;
					this.SendPropertyChanged("O_Start_Date");
					this.OnO_Start_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_End_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> O_End_Date
		{
			get
			{
				return this._O_End_Date;
			}
			set
			{
				if ((this._O_End_Date != value))
				{
					this.OnO_End_DateChanging(value);
					this.SendPropertyChanging();
					this._O_End_Date = value;
					this.SendPropertyChanged("O_End_Date");
					this.OnO_End_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_Status", DbType="NVarChar(20)")]
		public string O_Status
		{
			get
			{
				return this._O_Status;
			}
			set
			{
				if ((this._O_Status != value))
				{
					this.OnO_StatusChanging(value);
					this.SendPropertyChanging();
					this._O_Status = value;
					this.SendPropertyChanged("O_Status");
					this.OnO_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Station", DbType="NChar(10)")]
		public string Station
		{
			get
			{
				return this._Station;
			}
			set
			{
				if ((this._Station != value))
				{
					this.OnStationChanging(value);
					this.SendPropertyChanging();
					this._Station = value;
					this.SendPropertyChanged("Station");
					this.OnStationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_Track_Code", DbType="NVarChar(15)")]
		public string O_Track_Code
		{
			get
			{
				return this._O_Track_Code;
			}
			set
			{
				if ((this._O_Track_Code != value))
				{
					this.OnO_Track_CodeChanging(value);
					this.SendPropertyChanging();
					this._O_Track_Code = value;
					this.SendPropertyChanged("O_Track_Code");
					this.OnO_Track_CodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WO_Products")]
	public partial class WO_Products : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ıse_Record;
		
		private string _Track_Code;
		
		private string _Work_Order;
		
		private string _pr_Name;
		
		private System.Nullable<System.DateTime> _Start_Date;
		
		private System.Nullable<System.DateTime> _End_Date;
		
		private System.Data.Linq.Binary _Picture;
		
		private string _Status;
		
		private System.Nullable<System.DateTime> _Due_Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onıse_RecordChanging(int value);
    partial void Onıse_RecordChanged();
    partial void OnTrack_CodeChanging(string value);
    partial void OnTrack_CodeChanged();
    partial void OnWork_OrderChanging(string value);
    partial void OnWork_OrderChanged();
    partial void Onpr_NameChanging(string value);
    partial void Onpr_NameChanged();
    partial void OnStart_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnStart_DateChanged();
    partial void OnEnd_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnEnd_DateChanged();
    partial void OnPictureChanging(System.Data.Linq.Binary value);
    partial void OnPictureChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnDue_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnDue_DateChanged();
    #endregion
		
		public WO_Products()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ıse_Record", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ıse_Record
		{
			get
			{
				return this._ıse_Record;
			}
			set
			{
				if ((this._ıse_Record != value))
				{
					this.Onıse_RecordChanging(value);
					this.SendPropertyChanging();
					this._ıse_Record = value;
					this.SendPropertyChanged("ıse_Record");
					this.Onıse_RecordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Track_Code", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Track_Code
		{
			get
			{
				return this._Track_Code;
			}
			set
			{
				if ((this._Track_Code != value))
				{
					this.OnTrack_CodeChanging(value);
					this.SendPropertyChanging();
					this._Track_Code = value;
					this.SendPropertyChanged("Track_Code");
					this.OnTrack_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Work_Order", DbType="NVarChar(15)")]
		public string Work_Order
		{
			get
			{
				return this._Work_Order;
			}
			set
			{
				if ((this._Work_Order != value))
				{
					this.OnWork_OrderChanging(value);
					this.SendPropertyChanging();
					this._Work_Order = value;
					this.SendPropertyChanged("Work_Order");
					this.OnWork_OrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pr_Name", DbType="NVarChar(150)")]
		public string pr_Name
		{
			get
			{
				return this._pr_Name;
			}
			set
			{
				if ((this._pr_Name != value))
				{
					this.Onpr_NameChanging(value);
					this.SendPropertyChanging();
					this._pr_Name = value;
					this.SendPropertyChanged("pr_Name");
					this.Onpr_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Start_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Start_Date
		{
			get
			{
				return this._Start_Date;
			}
			set
			{
				if ((this._Start_Date != value))
				{
					this.OnStart_DateChanging(value);
					this.SendPropertyChanging();
					this._Start_Date = value;
					this.SendPropertyChanged("Start_Date");
					this.OnStart_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_End_Date", DbType="Date")]
		public System.Nullable<System.DateTime> End_Date
		{
			get
			{
				return this._End_Date;
			}
			set
			{
				if ((this._End_Date != value))
				{
					this.OnEnd_DateChanging(value);
					this.SendPropertyChanging();
					this._End_Date = value;
					this.SendPropertyChanged("End_Date");
					this.OnEnd_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Picture
		{
			get
			{
				return this._Picture;
			}
			set
			{
				if ((this._Picture != value))
				{
					this.OnPictureChanging(value);
					this.SendPropertyChanging();
					this._Picture = value;
					this.SendPropertyChanged("Picture");
					this.OnPictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(20)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Due_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Due_Date
		{
			get
			{
				return this._Due_Date;
			}
			set
			{
				if ((this._Due_Date != value))
				{
					this.OnDue_DateChanging(value);
					this.SendPropertyChanging();
					this._Due_Date = value;
					this.SendPropertyChanged("Due_Date");
					this.OnDue_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
